-- =====================================================================================
-- UPI Offline Payment PWA - Seed Data
-- Phase 1: MVP Foundations
-- Reference: CLAUDE.md
-- =====================================================================================
-- This file contains sample data for development and testing
-- DO NOT run this in production
-- =====================================================================================

-- =====================================================================================
-- SAMPLE MERCHANTS
-- =====================================================================================

INSERT INTO merchants (
  id,
  business_name,
  display_name,
  merchant_code,
  upi_id,
  phone_number,
  email,
  address_line1,
  city,
  state,
  postal_code,
  latitude,
  longitude,
  category,
  description,
  is_active,
  is_verified,
  supports_offline,
  nfc_enabled,
  qr_enabled
) VALUES
  (
    '11111111-1111-1111-1111-111111111111',
    'StarBucks Coffee',
    'StarBucks',
    'STARBUCKS001',
    'starbucks@paytm',
    '9876543210',
    'payments@starbucks.in',
    'MG Road, Brigade Road',
    'Bangalore',
    'Karnataka',
    '560001',
    12.9716,
    77.5946,
    'Cafe & Restaurant',
    'Premium coffee chain',
    true,
    true,
    true,
    true,
    true
  ),
  (
    '22222222-2222-2222-2222-222222222222',
    'Reliance Fresh',
    'Reliance Fresh',
    'RELIANCE001',
    'reliancefresh@okaxis',
    '9876543211',
    'payments@reliancefresh.in',
    'Indiranagar Main Road',
    'Bangalore',
    'Karnataka',
    '560038',
    12.9784,
    77.6408,
    'Grocery & Supermarket',
    'Fresh groceries and daily essentials',
    true,
    true,
    true,
    true,
    true
  ),
  (
    '33333333-3333-3333-3333-333333333333',
    'Metro Fuel Station',
    'Metro Fuel',
    'METRO001',
    'metrofuel@ybl',
    '9876543212',
    'payments@metrofuel.in',
    'Outer Ring Road',
    'Bangalore',
    'Karnataka',
    '560037',
    12.9352,
    77.6245,
    'Fuel Station',
    'Petrol, diesel, and convenience store',
    true,
    true,
    true,
    true,
    true
  ),
  (
    '44444444-4444-4444-4444-444444444444',
    'BigBazar Retail',
    'BigBazar',
    'BIGBAZAR001',
    'bigbazar@paytm',
    '9876543213',
    'payments@bigbazar.in',
    'Whitefield Main Road',
    'Bangalore',
    'Karnataka',
    '560066',
    12.9698,
    77.7500,
    'Retail & Department Store',
    'Fashion, groceries, and home essentials',
    true,
    true,
    true,
    false,
    true
  ),
  (
    '55555555-5555-5555-5555-555555555555',
    'MediPlus Pharmacy',
    'MediPlus',
    'MEDIPLUS001',
    'mediplus@okicici',
    '9876543214',
    'payments@mediplus.in',
    'Koramangala 5th Block',
    'Bangalore',
    'Karnataka',
    '560095',
    12.9352,
    77.6192,
    'Pharmacy & Healthcare',
    'Medicines and healthcare products',
    true,
    true,
    true,
    true,
    true
  );

-- =====================================================================================
-- SAMPLE DATA NOTES
-- =====================================================================================

-- For testing with real users:
-- 1. Users and wallets will be created when they register via the app
-- 2. You can manually insert test transactions after creating test users
-- 3. Device fingerprints will be generated by the app

-- Example test user creation (after Supabase Auth signup):
/*
INSERT INTO users (
  id,
  phone_number,
  full_name,
  is_verified
) VALUES (
  'auth-user-uuid-here', -- Replace with actual auth.users UUID
  '9999999999',
  'Test User',
  true
);

INSERT INTO wallets (
  user_id,
  upi_id,
  upi_provider,
  balance_paise
) VALUES (
  'auth-user-uuid-here',
  'testuser@paytm',
  'Paytm',
  500000 -- ₹5,000 for testing
);
*/

-- =====================================================================================
-- UTILITY FUNCTIONS FOR TESTING
-- =====================================================================================

-- Function: Generate test transaction
CREATE OR REPLACE FUNCTION create_test_transaction(
  p_sender_upi VARCHAR(100),
  p_receiver_upi VARCHAR(100),
  p_amount_paise INTEGER,
  p_is_offline BOOLEAN DEFAULT false
)
RETURNS UUID AS $$
DECLARE
  v_transaction_id UUID;
  v_sender_wallet_id UUID;
  v_receiver_wallet_id UUID;
BEGIN
  -- Get wallet IDs
  SELECT id INTO v_sender_wallet_id FROM wallets WHERE upi_id = p_sender_upi;
  SELECT id INTO v_receiver_wallet_id FROM wallets WHERE upi_id = p_receiver_upi;

  -- Create transaction
  INSERT INTO transactions (
    sender_wallet_id,
    receiver_wallet_id,
    amount_paise,
    transaction_type,
    payment_method,
    status,
    is_offline,
    description
  ) VALUES (
    v_sender_wallet_id,
    v_receiver_wallet_id,
    p_amount_paise,
    'payment',
    CASE WHEN p_is_offline THEN 'nfc' ELSE 'qr' END,
    CASE WHEN p_is_offline THEN 'pending' ELSE 'completed' END,
    p_is_offline,
    'Test transaction'
  )
  RETURNING id INTO v_transaction_id;

  -- Update balances if online transaction
  IF NOT p_is_offline THEN
    UPDATE wallets
    SET balance_paise = balance_paise - p_amount_paise
    WHERE id = v_sender_wallet_id;

    UPDATE wallets
    SET balance_paise = balance_paise + p_amount_paise
    WHERE id = v_receiver_wallet_id;
  END IF;

  RETURN v_transaction_id;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================================
-- DATA VERIFICATION QUERIES
-- =====================================================================================

-- Query to check all merchants
-- SELECT merchant_code, display_name, category, upi_id, is_active FROM merchants;

-- Query to check wallet balances
-- SELECT u.full_name, w.upi_id, w.balance_paise / 100.0 as balance_rupees, w.status
-- FROM wallets w
-- JOIN users u ON w.user_id = u.id;

-- Query to check daily limits
-- SELECT w.upi_id, dl.date, dl.transaction_count, dl.total_amount_paise / 100.0 as total_rupees
-- FROM daily_limits dl
-- JOIN wallets w ON dl.wallet_id = w.id
-- ORDER BY dl.date DESC;

-- Query to check recent transactions
-- SELECT
--   t.created_at,
--   ws.upi_id as sender,
--   wr.upi_id as receiver,
--   t.amount_paise / 100.0 as amount_rupees,
--   t.payment_method,
--   t.status,
--   t.is_offline
-- FROM transactions t
-- LEFT JOIN wallets ws ON t.sender_wallet_id = ws.id
-- LEFT JOIN wallets wr ON t.receiver_wallet_id = wr.id
-- ORDER BY t.created_at DESC
-- LIMIT 10;

-- =====================================================================================
-- END OF SEED DATA
-- =====================================================================================
